---
title: "class10hw"
author: "Yuan Lian"
date: "`r Sys.Date()`"
output: html_document
---

---
title: "Lecture 10 Homework Framework"
format: 
  html:
    self-contained: true
---

```{r setup, include=FALSE}
#| warning: false
library(tidyverse)     # loads the tidyverse tools
library(RPostgres)     # loads the database driver for PostgreSQL
library(connections)   # helps RPostgres work with RStudio
library(keyring)       # access to a local encrypted keychain for passwords


con <- connection_open(RPostgres::Postgres(),
          dbname = "syntheticmguh",
          host = "35.199.26.47",
          user = "hids502_student",
          password = key_get(service = "syntheticmguh", 
                             username = "hids502_student"),
          # Tell the driver to return very large integers as floating point (vs truncating them)
          bigint = "numeric")

knitr::opts_chunk$set(connection = "con")
```

# SyntheticMGUH As Big Data

For this homework you should act as if the report will be distributed, thus cannot return any PHI. **Do not include identifiers such as names or medical record numbers at the individual level in your results** Avoid returning individual rows unless you want to indicate the structure of a result set for some reason - you should be returning summary data at this point.

# Metadata

The Synthea data set holds a `imaging` table with meta data. The meta data describes the modality and type of imaging study.

-   Present a summary table of the `imaging` to provide an overview of the most common types of imaging studies performed. (Do not return individual rows, summarize and present the data.)

```{sql connection=con}
select bodysite_description, modality_description, sop_description, count(*) 
from imaging_studies
group by bodysite_description,modality_description,sop_description



```

## Asthma

-   Using free text search, locate all of the patients whose notes indicated they may have asthma. *Do not return the patients, but return a summary of the cohort*
-   How many of the patients you identified have a condition listed as 'asthma' in the `conditions` table?

```{sql connection=con}
select description, count(*) 
from conditions
where lower(description) like '%sthma%'
group by description
```

## Allergies

Some CT scans are done with "contrast", an intravenous form of dye to make the scan results clearer. People with shellfish allergies may have a similar reaction to contrast dye.

-   Allergies are available in Synthea in the allergy table, but in the real world this is not always so clear. Using only the `notes` table, find all the patients that have an shellfish allergy, and then using the `imaging` table determine home many of those patients have had a CT scan.

```{sql connection=con}
select  count(*) 
from notes
where lower(note_text) like '%shellfish allergy%'

```

```{sql connection=con}
select imaging_studies.modality_description, count(*)  from notes 
left join imaging_studies 
on notes.patient= imaging_studies.patient
where lower(notes.note_text) like '%shellfish allergy%'
and imaging_studies.modality_description ~* 'Computed Tomography'

group by imaging_studies.modality_description
```

# Patient Matching

-   How many patients in the Synthea database have the same first and last name? How many have the same first, last, gender and live in the same zip code?

Hint: You can do this with a `JOIN` approach or a `GROUP BY` approach. If you use the latter you may want to look at the `HAVING` command as a filter.

```{sql connection=con}
select p1.first,p2.first, p1.last, p2.last,count(DISTINCT p1.id) 
FROM patients AS p1
LEFT JOIN public.patients AS p2
 ON p1.last = p2.last and p1.first = p2.first
 
WHERE p1.last IS NOT NULL and p1.first IS NOT NULL

GROUP BY p1.last,p2.last, p1.first,p2.first

HAVING count(DISTINCT p1.id) > 1
ORDER BY count(DISTINCT p1.id) desc
limit 5

```

```{sql connection=con}
select p1.first,p1.last,p1.gender, p1.zip,count(DISTINCT p1.id) 
FROM patients AS p1
LEFT JOIN public.patients AS p2
 ON p1.last = p2.last and p1.first = p2.first and p1.gender=p2.gender and  p1.zip=p2.zip
 
WHERE p1.last IS NOT NULL and p1.first IS NOT NULL and p1.gender is not null and p1.zip is not null

GROUP BY p1.last, p1.first, p1.gender, p1.zip

HAVING count(DISTINCT p1.id) > 1


```

# Bonus

-   How many patients might have duplicate accounts based on middle name or first name errors? (You may not find any ... but show me how you would approach this.)

```{sql connection=con}
select p1.maiden, p1.first, count(DISTINCT p1.id) 
FROM patients AS p1
LEFT JOIN public.patients AS p2
 ON p1.maiden = p2.maiden and p1.first = p2.first
 
WHERE p1.maiden IS NOT NULL and p1.first IS NOT NULL

GROUP BY p1.maiden, p1.first

HAVING count(DISTINCT p1.id) > 1


```
